trigger: 
  branches: 
    include:
      - main
      - development
  paths: 
    include:
        - modules/app-configuration
        - modules/private-endpoint # dependency
pool:
  vmImage: windows-latest

variables:
  - group: bicep-module-configs

stages:
  - ${{ each environment in split(variables.environments, ',')}}:
    - template: '../../templates/module-deployment.yml'
      parameters:
        module: apim
        environment: ${{ environment }}