trigger: 
  branches: 
    include:
      - main
      - development
  paths: 
    include:
        - modules/app-configuration
        - modules/private-endpoint # dependency
pool:
  vmImage: windows-latest

variables:
  - name: environments
    value: dev,qa,prd

stages: 
  - ${{ each environment in split(variables.environments, ',')}}:
    - template: '../../templates/module-deployment.yml'
      parameters:
        module: app-configuration
        environment: ${{ environment }}
    