trigger: 
  branches: 
    include:
      - main
      - development
  paths: 
    include:
        - modules/app-configuration
        - modules/private-endpoint # dependency
pool:
  vmImage: windows-latest

# steps:
#   - task: PowerShell@2
#     inputs:
#       pwsh: true
#       targetType: inline
#       script: 
#         Write-Host $(service-principal)

stages: 
  - template: '../../templates/module-deployment.yml'
    parameters:
      environment: dev
      module: app-configuration
      variable_group: 'bicep-dev-module-configs'
    