trigger: 
  branches: 
    include:
      - main
      - development
  paths: 
    include:
        - modules/app-configuration
        - modules/private-endpoint # dependency
pool:
  vmImage: windows-latest

variables:
  - group: bicep-dev-module-configs


steps:
  - task: Bash@3
    inputs:
      script: 
        echo $(service-principal)

# stages: 
#   - template: '../../templates/module-deployment.yml'
#     parameters:
#       environment: dev
#       module: app-configuration
#       variable_group: 'bicep-dev-module-configs'
    