name: ''
on: push
jobs: 
    bicep-build-and-deploy:
        name: bicep build and deploy
        runs-on: ubuntu-latest
    
        steps:
          # Checks out a copy of your repository on the ubuntu-latest machine
          - name: Checkout code
            uses: actions/checkout@v2
    
          # Install the latest release of the bicep CLI
          - name: Install bicep CLI
            run: |
              curl -Lo bicep https://github.com/Azure/bicep/releases/latest/download/bicep-linux-x64
              chmod +x ./bicep
              sudo mv ./bicep /usr/local/bin/bicep
              bicep --help
               
          # Transpile bicep file into ARM template
          - name: Build ARM Template from bicep file
            run: |
              bicep build ./main.bicep
          
          # Stop here if you only want to do "CI" which just generates the 
          # build artifact (ARM Template JSON)
    
          # Login to Azure
          - name: Azure Login
            uses: azure/login@v1
            with:
              creds: ${{ secrets.AZURE_CREDENTIALS }} 
    
          # Emit template what-if to show what template will do
          - name: Run what-if
            uses: azure/CLI@v1
            with:
              inlineScript: |
                az account show
                az deployment group what-if -f ./main.json -p ./parameters.json -g my-rg
    
          # You may want a human approval in between the what-if step 
          # and the deploy step to evaluate output before deployment
    
          # Deploy template
          - name: Deploy template
            uses: azure/CLI@v1
            with:
              inlineScript: |
                az account show
                az deployment group create -f ./main.json -g my-rg
