trigger: 
  branches: 
    include:
      - main
      - development
  paths: 
    include:
        - modules/log-analytics-workspace/*
  
pool:
  vmImage: windows-latest

variables:
  - name: environments
    value: dev,qa,prd

stages:
  - ${{ each environment in split(variables.environments, ',') }}:
    - template: '../../templates/module-deployment.yml'
      parameters:
        module: log-analytics-workspace
        environment: ${{ environment }}
        subscription: Assimalign SA (${{ upper(environment) }})
    