trigger: 
  branches: 
    include:
      - main
      - development
  paths: 
    include:
        - modules/public-ip
pool:
  vmImage: windows-latest

variables:
  - name: environments
    value: dev

stages:
  - ${{ each environment in split(variables.environments, ',') }}:
    - template: '../../templates/module-deployment.yml'
      parameters:
        module: public-ip
        environment: ${{ environment }}
        subscription: DSB 1.0 Azure DevOps SA (${{ upper(environment) }})
    
    