trigger: 
  branches: 
    include:
      - main
      - development
  paths: 
    include:
        - src/schemas

pool:
  vmImage: windows-latest

variables:
  - group: bicep.release.variables

steps:
- task: AzurePowerShell@5
  displayName: 'Upcert Bicep JSON Schemas'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  inputs:
    azureSubscription: $(azure-devops-service-principal)
    azurePowerShellVersion: 'LatestVersion'
    ScriptType: 'FilePath'
    ScriptPath: 'modules.schemas.push.ps1'
    ScriptArguments:
      -storageAccountName $(azure-schema-stgact)
      -storageAccountResourceGroup $(azure-schema-stgact-rg)
      -storageAccountContainerName json