trigger: 
  branches: 
    include:
      - main
      - development
  paths: 
    include:
        - modules/public-dns-zone
pool:
  vmImage: windows-latest

variables:
  - group: bicep-module-variables

steps:  
- task: AzurePowerShell@5
  displayName: "Upcert Bicep Modules"
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  inputs:
    azureSubscription: $(service-principal)
    preferredAzurePowerShellVersion: "10.3.0"
    pwsh: true
    ScriptType: "FilePath"
    ScriptPath: "deploy.ps1"
    ScriptArguments:
      -moduleName public-dns-zone
      -storageAccountName $(storage-account)
      -storageAccountContainerName $(storage-account-conatiner)
      -storageAccountResourceGroup $(storage-account-resource-group)
      -containerRegistryName $(container-registry)
      -containerRegistryResourceGroup $(container-registry-resource-group)
    