parameters:
  - name: module

variables:
- group: bicep-qa-module-configs

stages:
  - stage: qa
    displayName: Release - QA
    jobs:
      - deployment: release
        environment: 'Development'
        strategy:
          runOnce:
            deploy:
              steps:
              - checkout: self
                displayName: Checkout
              
              - task: AzurePowerShell@5
                displayName: "Upcert Bicep Modules"
                condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
                inputs:
                    azureSubscription: $(service-principal)
                    preferredAzurePowerShellVersion: "10.3.0"
                    pwsh: true
                    ScriptType: "FilePath"
                    ScriptPath: "deploy.ps1"
                    ScriptArguments:
                      -moduleName ${{ parameters.module }}
                      -storageAccountName $(storage-account)
                      -storageAccountContainerName $(storage-account-container)
                      -storageAccountResourceGroup $(storage-account-resource-group)
                      -containerRegistryName $(container-registry)
                      -containerRegistryResourceGroup $(container-registry-resource-group)