parameters:
- name: environment
  type: string
  values:
  - dev
  - qa
  - uat
  - prd

# - name: subscription
#   type: string

- name: module
  type: string

stages:
  - stage: ${{ parameters.environment }}
    displayName: Release - ${{ upper(parameters.environment) }}
    jobs:
      - deployment: bicep_push
        displayName: 'Bicep: Module Push - ${{ parameters.module }}'
        variables:
        - group: 'bicep-${{ parameters.environment }}-module-configs'
        environment: 'Development'
        strategy:
          runOnce:
            deploy:
              steps:
              - checkout: self
                displayName: Checkout
              - task: AzurePowerShell@5
                displayName: "Upcert Bicep Modules"
                condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/heads/main'), eq(variables['Build.SourceBranch'], 'refs/heads/development')))
                inputs:
                  azureSubscription: $[variables.service-principal]
                  azurePowerShellVersion: LatestVersion
                  pwsh: true
                  ScriptType: "FilePath"
                  ScriptPath: "deploy.ps1"
                  ScriptArguments:
                    -moduleName ${{ parameters.module }}
                    -storageAccountName $(storage-account)
                    -storageAccountContainerName $(storage-account-container)
                    -storageAccountResourceGroup $(storage-account-resource-group)
                    -containerRegistryName $(container-registry)
                    -containerRegistryResourceGroup $(container-registry-resource-group)

