trigger: 
  branches: 
    include:
      - main
      - development
  paths: 
    include:
      - modules/virtual-machine

pool:
  vmImage: windows-latest

variables:
  - name: environments
    value: dev,stg,prd

stages:
  - ${{ each environment in split(variables.environments, ',') }}:
    - template: '../../templates/module-deployment.yml'
      parameters:
        module: virtual-machine
        environment: ${{ environment }}
        subscription: Mint DevOps SA (${{ upper(environment) }})